language: php

php:
  - 5.6
  - nightly
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

install:
  - composer install

script: ./venodr/bin/phpunit tests/unit

after_script: php vendor/bin/coveralls -v
