language: php

php:
  - 5.6
  - nightly
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm

install:
  - composer install

script: phpunit tests/unit

after_success: php vendor/bin/coveralls -v
